_target_: src.models.img_encoder.AGPNeck

align_res_layer:
  _target_: src.models.img_encoder.neck.AlignRes
  mode: "upsample"
  scale_factors: [1, 2]
  in_channels: ${model.in_c.neck}

prepare_c_layer:
  _target_: src.models.img_encoder.neck.PrepareChannel
  in_channels: ${model.in_c.neck}
  interm_c: ${get_neck_interm_c:${model.backbone._target_}}
  out_c: ${model.out_c.neck}
  mode: "doubleconv"
  tail_mode: "conv2d"