defaults:
  - _self_
  - attnlayer: transformer.yaml

classname: src.models.layers.TorchGeomAttnBlock
mode: torchgeom
in_c: ${model.out_c.vt}
mid_c: ${model.out_c.vt}
out_c: ${model.out_c.vt}
attnlayer: null
residual: True
widening_factor_mlp: 2
dropout_mlp: 0.0