defaults:
  - _self_
  - backbone: efficientnet.yaml
  - neck: agp.yaml
  - projector: camprojector.yaml
  - temporal: null
  - view_transform: gs_sparse.yaml
  - autoencoder: sparse_unet.yaml
  - heads: sparse_convn.yaml

_target_: src.models.Coarse_fine
in_shape: 
    projector: [200,200,8]
    spatial_bounds: ${model.projector.spatial_bounds}

voxel_ref: "spatial"

in_c:
  neck: ${get_in_c_neck:${model.backbone._target_}}
  vt: ${model.out_c.base_neck}

out_c: 
  base_neck: 128
  N_group: 1
  neck: ${mult:${model.out_c.base_neck},${model.out_c.N_group}}
  vt: ${model.out_c.base_neck}
  autoencoder: ${model.out_c.vt}

sampled_kwargs:
  # Coarse
  N_coarse:  2_500
  mode: rnd_pillars
  val_mode: dense
  patch_size: 1
  compress_height: False
  # Fine
  with_fine: True
  valid_fine: False
  N_fine: 2_500
  N_anchor: 100
  fine_patch_size: 9
  fine_thresh: 0.1
  # Temporal
  temp_thresh: -5